services:
  - name: render
    type: web
    env: python
    repo: https://github.com/masamichi0418/render.git 
    branch: master
    plan: free
    region: singapore
    buildCommand: pip3 install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn render.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: postgres://app_user:M7HOOxA2DMqhuY00QrfxBtGM7i49AWNA@dpg-cctrlfqen0hklj1nbj40-a/django_baby_db_name_28hd
        fromDatabase:
          name: test_db
          property: connectionString

databases:
  - name: test_db
    plan: free
    region: singapore