# Generated by Django 3.2 on 2021-09-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='registered_data',
            new_name='registered_date',
        ),
    ]
